name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Package
        run: make enapter-grafana-plugins.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: enapter-grafana-plugins.tar.gz
